dadosPerguntas = [
    {"texto": "A Estátua da Liberdade fica em Washington DC", "resposta": "falso"},
    {"texto": "Tartarugas podem respirar através do bumbum", "resposta": "verdadeiro"},
    {"texto": "O rei do rock and roll, Elvis Presley, morreu de overdose de drogas", "resposta": "falso"},
    {"texto": "Austrália é o maior país do mundo", "resposta": "falso"},
    {"texto": "O olho humano é capaz de distinguir mais de um milhão de cores", "resposta": "verdadeiro"},
    {"texto": "Os gatos podem ver no escuro completo", "resposta": "falso"},
    {"texto": "A torre Eiffel foi construída em menos de um ano", "resposta": "verdadeiro"},
    {"texto": "A Mona Lisa foi roubada do Louvre em 1911", "resposta": "verdadeiro"},
    {"texto": "O Google foi fundado em 1999", "resposta": "falso"},
    {"texto": "Um 'calcanhar de Aquiles' refere-se a uma fraqueza em uma pessoa", "resposta": "verdadeiro"},
    {"texto": "O nome completo do famoso personagem de videogame Mario é Mario Mario", "resposta": "verdadeiro"},
    {"texto": "O menor país do mundo é a Cidade do Vaticano", "resposta": "verdadeiro"},
    {"texto": "O Lago Ness é um lago na Escócia conhecido por abrigar um monstro lendário", "resposta": "verdadeiro"},
    {"texto": "Cães só enxergam em preto e branco", "resposta": "falso"},
    {"texto": "Os pássaros são animais de sangue quente", "resposta": "verdadeiro"},
    {"texto": "A rainha Elizabeth II do Reino Unido nasceu na Inglaterra", "resposta": "verdadeiro"},
    {"texto": "A cidade de Veneza na Itália foi construída sobre uma rede de canais", "resposta": "verdadeiro"},
    {"texto": "O autor de 'O Senhor dos Anéis', J.R.R. Tolkien, inventou o idioma élfico para seus livros", "resposta": "verdadeiro"},
    {"texto": "O ex-presidente dos Estados Unidos, Barack Obama, nasceu no Havaí", "resposta": "verdadeiro"},
    {"texto": "Um 'unicórnio' é uma criatura mitológica com um chifre em sua cabeça", "resposta": "verdadeiro"},
    {"texto": "O chocolate faz as pessoas felizes porque contém substâncias químicas que estimulam a liberação de endorfinas no cérebro", "resposta": "verdadeiro"},
    {"texto": "O presidente dos Estados Unidos, Joe Biden, é canhoto", "resposta": "verdadeiro"},
    {"texto": "O grito de guerra 'Banzai!' significa 'vitória' em japonês", "resposta": "falso"},
    {"texto": "O Titanic foi afundado por um iceberg na costa da Irlanda em 1912", "resposta": "verdadeiro"}
]
